package com.example.Student_library_management_system.DTOs;

public class AuthorEntryDto {
    // this is just an object that will used to take request from postman.

    // it will contain the parameter that we want to send from postman.

    // id is not here, it will be auto generated by spring
    private String name;
    private int age;
    private String phNo;
    private String country;
    private double rating;

    public AuthorEntryDto() {
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getPhNo() {
        return phNo;
    }

    public void setPhNo(String phNo) {
        this.phNo = phNo;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public double getRating() {
        return rating;
    }

    public void setRating(double rating) {
        this.rating = rating;
    }
}
